openapi: 3.0.3
info:
  title: Simple Messenger API
  version: "1.0"

servers:
  - url: https://api.example.com/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        created_at:
          type: string
          format: date-time

    AuthRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        token:
          type: string

    Conversation:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
          properties:
            id:
              type: integer
            title:
              type: string
            created_at:
              type: string
              format: date-time

    MessageRequest:
      type: object
      required:
        - conv_id
        - content
      properties:
        conv_id:
          type: integer
        content:
          type: string

    MessageResponse:
      allOf:
        - $ref: '#/
